name: Create release branch and PRs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: automation-test-master # todo change to master
      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=branch::"release/$(date +%Y-%m-%d)"
      - name: Create release branch and merge develop
        run: |
          git checkout -b ${{ steps.vars.outputs.branch }}
          git merge origin/develop
          git push
      - name: Show merge commit
        run: git --no-pager show
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: release branch for develop
          base: develop
          branch: ${{ steps.vars.outputs.branch }}
          title: develop ${{  steps.vars.outputs.branch }}
